---
title: "proj2.cho"
author: "Sung In Cho (sc4393)"
date: "10/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE error=FALSE}
# required package
library(png)
library(dtplyr)
library(dplyr)
library(DT)
library(lubridate)
library(shiny)
library(choroplethr)
library(choroplethrZip)
library(ggplot2)
library(ggmap)
library(readr)
library(plyr)
library(tmap)
library(sf)
library(leaflet)
library(raster)
library(spData)
library(shinydashboard)
library(shinythemes)
library(leaflet.extras)
library(magrittr)
library(gmapsdistance)
library(plotly)
library(googleway)
library(mapview)
library(shinyBS)
library(shinyjs)
library(htmltools)
library(bsplus)
library(shinyWidgets)
library(shinycssloaders)
library(shinycustomloader)
library(shinyFeedback)
register_google(key="AIzaSyC37N09VQDrlBw-myPO42263tqOj_He9xA")
```

```{r}
setwd("/Users/davidcho/ADS proj2")
# import data
rest <- read.csv("restaurant_NYC.csv") 
land <- read.csv("final_data.csv")
```

```{r}
# temporary merged data set
colnames(rest)[c(3,7,8)] <- c("Name","lat", "lon") 
newrest<-data.frame(rest,a=NA,b=NA,c=NA)
newrest <- newrest[,c(1,2,3, 9,6,5,7,8,4,10,11,12,13,14,15,16,17,18 )]
colnames(newrest) <- colnames(land)
place <- rbind(land, newrest)
place$type <- toupper(place$type)
place[place$type=="LANDMARKS",]$type <- "LANDMARK"
```

```{r}
# Icon List
mapIcons <- iconList(
  LIBRARY = makeIcon("/Users/davidcho/ADS proj2/library.png", 18, 18),
  MUSEUM = makeIcon("/Users/davidcho/ADS proj2/museum.png", 18, 18),
  FILM = makeIcon("/Users/davidcho/ADS proj2/film.png", 18, 18),
  LANDMARK = makeIcon("/Users/davidcho/ADS proj2/landmark.png", 18, 18),
  RESTAURANT= makeIcon("/Users/davidcho/ADS proj2/restaurant.png", 18, 18)
)
```
