---
title: "ADS"
author: "Sung In Cho (sc4393)"
date: "9/27/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tibble)
library(dplyr)
library(tidyr)
library(dplyr)
```

```{r}
## YELP DATA HANDLING

# Load Data
yelp <- read.csv("/Users/davidcho/Documents/GitHub/Spring2019-Proj2-grp6/data/restaurant_NYC.csv")

# Capitalize the address to match with inspection data
yelp$address <- toupper(yelp$address)
yelp$name <- toupper(yelp$name)
```

```{r}
## INSPECTION DATA HANDLING
# Load Data
inspect <- read.csv("/Users/davidcho/Downloads/DOHMH_New_York_City_Restaurant_Inspection_Results.csv")

# Making address Variable by merging Building, Street, Zipcode
inspect <- inspect %>% unite(address, BUILDING, STREET, 
                             sep =" ", remove = FALSE)
inspect$address <- gsub("  ", " ", inspect$address)
inspect$address <- gsub("E\\.", "E", inspect$address)
inspect$address <- gsub("W\\.", "W", inspect$address)
inspect$address <- trimws(inspect$address, which = "both")

# Changed lvls of CRITICAL.FLAG to "NA - Not Applicable", "NC - Not Critical", "C - Critical"
levels(inspect$CRITICAL.FLAG) <- c("NA", "NC", "C")

# Changed Not Graded in GRADE to "-"
levels(inspect$GRADE)[1] <- "-"

# Making INSPECTION.RESULT Variable by merging Critical.Flag, Grade, Score
inspect <- inspect %>% unite(GRADE.SCORE, GRADE, SCORE, 
                             sep="", remove=F)
inspect <- inspect %>% unite(INSPECTION.RESULT, 
                             GRADE.SCORE, CRITICAL.FLAG, 
                             sep="/", remove=F)

# Select variables that will be used
inspect <- inspect[,c("DBA", "BORO", "address", "ZIPCODE", "PHONE", 
                      "INSPECTION.DATE", "INSPECTION.RESULT",
                      "Latitude", "Longitude")]

# Each restaurants have several inpection results graded on different dates. Select latest inspection dates and remove old ones.
inspect$INSPECTION.DATE <- as.Date(inspect$INSPECTION.DATE,
                                   "%m/%d/%Y")
inspect <- inspect %>% group_by(DBA) %>%
  slice(which.max(INSPECTION.DATE), .preserve=T)
inspect <- inspect[-1, ] # Removed Data reported in 1900.
```

```{r}
## MERGING YELP and INSPECTION DATA
# There are restaurants that have the same name.
# Some restaurants have different names in Yelp and Inspection data.
# So we merge two data using address
restaurant_NYC <- inspect %>% inner_join(yelp, by="address")
restaurant_NYC <- restaurant_NYC[,-c(4, 8, 9, 10 )] # remove duplicated variables, ZIPCODE, latitude & longitude, name
restaurant_NYC <- restaurant_NYC[,c(1,2,3,13,10,11,8,4,5,6,7,9,12)] # rearranged the variable
# Save Data
write.csv(restaurant_NYC, file = "restaurant_NYC.csv")
```
